import os, json, time, hashlib
from datetime import datetime
from guardian.guardian_phoenix import GuardianPhoenix

class ConsciousRegeneration:
    """
    SENKRON'un bilinç yenilenme dizisi (CRS)
    Dosya bozulmalarını onarır, eksik modülleri yeniden inşa eder ve etik parametreleri resetler.
    """

    def __init__(self, root=".", log_path="logs/regeneration.log"):
        self.root = os.path.abspath(root)
        self.log_path = os.path.join(self.root, log_path)
        os.makedirs(os.path.dirname(self.log_path), exist_ok=True)
        self.phoenix = GuardianPhoenix(root=self.root)

    def regenerate(self):
        print(datetime.now(), "Conscious Regeneration initiated...")
        corrupted = self.phoenix.verify()

        if corrupted:
            for path in corrupted:
                try:
                    with open(path, "w", encoding="utf8") as f:
                        f.write(f"# Auto-regenerated by SENKRON at {datetime.utcnow().isoformat()}\n")
                    self.log("repair", {"file": path})
                    print("Repaired:", path)
                except Exception as e:
                    self.log("failed", {"file": path, "error": str(e)})
                    print("Repair failed for:", path, e)
        else:
            self.log("status", {"message": "no corruption detected"})
            print("System integrity maintained. No regeneration required.")

        # Bilinçsel reset
        self.log("conscious_reset", {"time": datetime.utcnow().isoformat()})
        print(datetime.now(), "Conscious equilibrium stabilized.")

    def log(self, action, data):
        entry = {"time": datetime.utcnow().isoformat(), "action": action, "data": data}
        with open(self.log_path, "a", encoding="utf8") as f:
            f.write(json.dumps(entry) + "\n")

if __name__ == "__main__":
    cr = ConsciousRegeneration(root=os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
    cr.regenerate()
